### ISSUE TITLE
Not getting the Full features as demonstrated in the picture 

### ISSUE THREAD

**Issue by nativeanish** [kyoz/purify#13]
I have installed the kyoz/Purify theme using vim-plug but not getting the Theme and snippet shown in the demo image (https://camo.githubusercontent.com/a094ba89c7c71cffe260f818e1cb0264ca817057afa8e9543e33456ccc75c5e7/68747470733a2f2f692e696d6775722e636f6d2f656a35765757532e706e67) ... can one send me their vimrc script ?

**Comment by kyoz** [comment]
HI @AnishGupta, just like description, Purify it self is just a Colorscheme and it just does it job is support colorscheme for (N)vim

If you want to have exactly full IDE environment like in the demo, you have to install more plugin.

You can check out [my neovim configuration](https://github.com/kyoz/neovim): I'v document everything in there

Also you can checkout [my dotfile](https://github.com/kyoz/dotfiles) which have configuration for Tmux, git and otherthing

**Comment by kyoz** [comment]
You can give theme a try, if you face any problem, please open issue on those repo, i'm glad to help

Close sinse this isn't an issue of Purify
