### ISSUE TITLE
No colors showing

### ISSUE THREAD

**Issue by EthanRodrigo** [kyoz/purify#14]
I have recently installed purify in my machine, but now its shows no syntax highlighting.
Following is in my .vimrc file 

call plug#begin('~/.vim/plugged')
" purify theme
Plug 'kyoz/purify', { 'rtp': 'vim' }
call plug#end()

syntax on
colorscheme purify

even though all are set it still doesn't show any syntax highlighted.

**Comment by kyoz** [comment]
Hello @ethan-rod6 , in order to get the plugin install you have to call `:PlugInstall`. Also ensure that you have install [VimPlug](https://github.com/junegunn/vim-plug) so you can run `:PlugInstall`. After installed. Quit and reopen vim and the theme will get apply.

Sorry for the late response, i didn't get notified from github. Please try and let me know if it work. Glad to help. :cat:

**Comment by EthanRodrigo** [comment]
@kyoz I'm sorry but it doesn't work either. I have install purify with `:PlugInstall`.
When I run `:PlugInstall` the output is like  
```
- Finishing ... Done!                    
- purify: Already installed
```

**Comment by kyoz** [comment]
That seem you have installed it correctly. Can you screenshot your current view with purify theme. 

Then try this command in vim (to see if it have any change):

```
:colorscheme default
```

**Comment by kyoz** [comment]
If possible, please sent me a file that you are using to test Purify. You can strip down all data, just leave a few lines for me to test is enough. :smile:

**Comment by EthanRodrigo** [comment]
This is the current view if I enable purify. https://imgur.com/7pjHDMq (I donno how to post a image here. So I use third party website to convert it to a url.). And that's it.I'm testing `.vimrc` file.

**Comment by kyoz** [comment]
Hmm, that's odd. I'm just trying on my konsole and it working.

![image](https://user-images.githubusercontent.com/29815830/137090266-7a8da632-2908-4901-809c-c8f12958a13a.png)

Can you give my config a try:

```
"  _   __
" | | / /
" | |/ / _   _  ___ ____
" |    \| | | |/ _ \_  /  Author: Kyoz
" | |\  \ |_| | (_) / /   Github: github.com/banminkyoz
" \_| \_/\__, |\___/___|  Email : banminkyoz@gmail.com
"         __/ |
"        |___/

call plug#begin('~/.vim/plugged')
Plug 'kyoz/purify', { 'rtp': 'vim' }
call plug#end()

syntax on
colorscheme purify

" DISPLAY {{{
set encoding=utf8
set nowrap "---------------------------------- do not automatically wrap on load
set colorcolumn=80 "---------------------------------------- 80 line column show
set nospell "-------------------------------------------------- Disable spelling
set formatoptions-=t "--------------- Do not automatically wrap text when typing
set listchars=tab:\|\ ,trail:▫
set formatoptions=tcqronj "-------------------- Set vims text formatting options
set title "-------------------------------------- Let vim set the terminal title
set updatetime=500 "-------------------------------- Redraw the status bar often
set list "--------------------------------------------- Show trailing whitespace
set listchars=tab:•\ ,trail:•,extends:»,precedes:« "-- Unprintable chars mapping
set showcmd	"--------------------------------------- Display incomplete commands
set termencoding=utf-8 "------------------------------------------- Always utf-8
set fileencoding=utf-8
set hid "---------------------------------- Buffer becomes hidden when abandoned
set shortmess+=c
set cmdheight=1 "--------------------------- Just need one line for command line
set laststatus=2 "-------------------------------------- Always show status line
set showtabline=2 "----------------------------------------- Always show tabline
set noshowmode "--------------------------- Hide default mode text (e.g. INSERT)
set display+=lastline "--------------------- As must as possible of the lastline
set previewheight=3 "------------------------------------ Smaller preview height
" }}}

" SYNTAX {{{
syntax on "---------------------------------------------- Enable Syntax for Code
syntax enable
set foldmethod=manual "---------------------------------- Support fold by indent
" }}}

" FILE, FILE'S TYPES {{{
set autoread "---------------------------------------- Auto reloaded Edited File
set noswapfile "------------------------------------------ Dont create wrap file
set nobackup "------------------------------------------------- Dont save backup
filetype plugin on "--------------------------------------------- Turn on plugin
let g:jsx_ext_required = 1 "------------------------- Dont detect js file as jsx
" }}}

" TYPINGS {{{
set backspace=indent,eol,start "----------------- Allow backspace in insert mode
" }}}

" TAB, INDENT {{{
set tabstop=2 "---------------------------------------------- 2 spaces for 1 tab
set softtabstop=2
set shiftwidth=2
set expandtab "------------------------------------------ Add tab in insert mode
set smarttab
filetype indent on "------------------------------------- Turn on default indent
set autoindent
set smartindent
" }}}

" SEARCH {{{
set hlsearch "------------------------------------------ Highlight search result
set incsearch "------------------------------------------ Allow Insert higtlight
" }}}

" FORMAT {{{
set nrformats-=octal "----------------------------------- Format number as octal
" }}}

" UNDO {{{
set undolevels=100 "------------------------------- Default is 1000 -> Too large
set undoreload=1000 "----------------------------- Default is 10000 -> Too large
set undodir=~/.config/nvim/undodir "--------------- Default folder for undo step
" }}}

" FOLD SETTINGS {{{
aug vim_folding
  au!
  au FileType vim setlocal foldmethod=marker
aug END
" }}}

" MAPPINGS {{{
let mapleader = "\<Space>" 
let maplocalleader = "\\"

" Use jk to exit insert mode instead of esc
inoremap jk <ESC>l

" Use black hole for delete. Don't want to store in register with dd.
" For cut, use visual and x instead
nnoremap d "_d
vnoremap d "_d

" Save and close current buffer
nnoremap <leader>z :wa<CR>:bd<CR>

" Buffer moving
nnoremap gB :bprevious <CR> 
nnoremap gb :bnext <CR>

" Disable Ctrl-Z
nnoremap <c-z> <NOP>

" Disable arrow keys (Vim don't need this)
nnoremap <Up> <NOP>
nnoremap <Down> <NOP>
nnoremap <Left> <NOP>
nnoremap <Right> <NOP>
" }}}

```

P/s :You can copy the image and paste it directly to github.

**Comment by kyoz** [comment]
If the purify theme not work, vim will also try the default theme, it will look somehow like this:

![image](https://user-images.githubusercontent.com/29815830/137090949-8d5c0000-6391-490b-83c9-2f43c548036f.png)

But in your image i didn't see any syntax.

To double check and try this. Open a file with vim, then type these command:

```
:syntax on
```

and then try a few built-in theme to see if it work:

```
:color default
:color morning
:color purify
```

**Comment by kyoz** [comment]
Also, purify also support color for Konsole, which you can easily to install [here](https://github.com/kyoz/purify/tree/master/konsole).

If nothing work you can also try to install it to set purify color for Konsole and try again

**Comment by EthanRodrigo** [comment]
I download and installed the purify for Konsole, It's working now. Btw Thank you for helping!

And what konsole are you using? I mean there is a bottom line. Is it the konsole or any other?

**Comment by kyoz** [comment]
You mean this?
![image](https://user-images.githubusercontent.com/29815830/138675483-5b19417c-31ee-4cd9-8134-b365a03e929f.png)

**Comment by EthanRodrigo** [comment]
yes

**Comment by kyoz** [comment]
If so, that is [vim-airline](https://github.com/vim-airline/vim-airline) which also supported by purify, You can config like [this](https://github.com/kyoz/purify/tree/master/vim#airline)

Also, vim-airline support lot's of [themes](https://github.com/vim-airline/vim-airline/wiki/Screenshots) which you can pick for your taste.

**Comment by EthanRodrigo** [comment]
Thanks I'll look into that

**Comment by kyoz** [comment]
Also i'll tried a lots of plugins and pick out most helpful plugins (for my work) in [here](https://github.com/kyoz/neovim). 

[This](https://github.com/kyoz/neovim/blob/master/configs/init.vim) is the list of all plugins i'v used. You can try and pick what you want :cat: 

Hope it help. So i'll close this issue. If you have any issue feel please to open new one. :cat:

**Comment by EthanRodrigo** [comment]
Sure
