### ISSUE TITLE
gVim support?

### ISSUE THREAD

**Issue by mike-m118** [kyoz/purify#3]
Hey kyoz, really love the theme and it looks great in the terminal version of vim. However, trying to use it in gVim results in a white background. Any thoughts on how to add gvim support? i'm just starting to use vim, so not super familiar with all the options myself!

**Comment by kyoz** [comment]
Hi @mike-m118 ,  I'm not having window environment here but in MacOS, i'v tried it on MacVim (Which similar to gVim on Window) and it work fine.

If you don't use any Vim Plugin Management like `vim-plug` or `vundle` you can try this way to install Purify on gVim

First you need copy the theme to your `plugins` folder. The structure is somehow like this:

![image](https://user-images.githubusercontent.com/29815830/87843829-dda50e00-c8e1-11ea-897b-69ad8ad6794d.png)

Then set this in your vimrc
```
let g:onedark_termcolors=256
:silent! colorscheme purify "--------------------------------- Set onedark theme
hi Normal guibg=NONE ctermbg=NONE "---------------- Transparent background color
```

Please give it a try and let me know if it work. Btw,  i think you should give [vim-plug](https://github.com/junegunn/vim-plug) a try. It help you install & maintain your plugins easily. 😄

**Comment by kyoz** [comment]
I'm close this cause this issue seem solved. Please open other issue if you have any problem when using Purify. :smile:
