### ISSUE TITLE
Highlighting

### ISSUE THREAD

**Issue by ghost** [kyoz/purify#4]
Hi

I am getting this weird highlighting. Do you know how to fix this?
<img width="711" alt="Screen Shot 2020-10-14 at 9 05 18 PM" src="https://user-images.githubusercontent.com/63811869/96061343-f7aea800-0e60-11eb-828e-f6704b4dfa86.png">

Thanks

**Comment by kyoz** [comment]
hi @bscuron 

This problem is because the italic support of the font.

You can turn it off or change another font which support italic for fully feature.

You can see this [issue](https://github.com/kyoz/purify/issues/1) for more information :smile:

**Comment by kyoz** [comment]
I'm close this cause this issue seem solved. Please open other issue if you have any problem when using Purify. :smile:
