### ISSUE TITLE
Theme idea

### ISSUE THREAD

**Issue by Meilky** [kyoz/purify#6]
I think it would be nice to have a theme for ncmpcpp

Thank you

**Comment by kyoz** [comment]
Hello @Meilky, that's good idea, i'v tried ncmpcpp in the past, it's really cool.

I'll try to implement ncmpcpp soon :D

**Comment by kyoz** [comment]
There you go @Meilky [Purify Ncmpcpp](https://github.com/kyoz/purify/tree/master/ncmpcpp)

But due to the lack of config and my knowledge, this is my best i can do, if you know more about ncmpcpp config, please open pull request.

:cat:

**Comment by Meilky** [comment]
I saw what you did and I think I can't do better.

That's awesome xD

**Comment by Meilky** [comment]
I have a bug when openning ncmpcpp.

Artist, Title and Album columns display <empty>
but the time column give me the time

![ncmpcpp](https://user-images.githubusercontent.com/53416287/102240747-31824600-3ec6-11eb-8c78-d6b496a0e75e.png)

I use zsh with your color scheme on it

I don't know, but could it be a mpd config error in my config?

**Comment by Meilky** [comment]
Ok I found the problem,
My mp3 files don't have artist name and title in metadata

**Comment by kyoz** [comment]
What terminal are you using, you have to patch the terminal color to get same colors as me

**Comment by Meilky** [comment]
I use the default one from kali-linux.

**Comment by Meilky** [comment]
I downloaded your theme for the gnome-term and everything is ok.

**Comment by kyoz** [comment]
Ok @Meilky , so imma closing this. Hope ncmpcpp has a great update with new config structure, and support hex or rgba color soon :cat:
